### ISSUE TITLE
Linux implementation

### ISSUE THREAD

**Issue by leoguti85** [nphdang/GE-FSG#1]
Hi,
Do you have a Linux implementation of this algorithm?

Thank you.

**Comment by nphdang** [comment]
Hi @leoguti85,
Please use this implementation for Linux: https://github.com/nphdang/GE-FSG/tree/master/For_Linux
It was tested with Ubuntu 18.06, Mono 5.20.1, Python 3.6 (Anaconda), and gensim 3.4.
Cheers.
