### ISSUE TITLE
can not open fsg_miner.exe

### ISSUE THREAD

**Issue by iiphenoix** [nphdang/GE-FSG#3]
My computer have install Microsoft .NET Framework 4,but still can not open fsg_miner.exe
Could you tell me how can I do?Thank you very much.

**Comment by nphdang** [comment]
Hi, are you using Windows or Linux? If you are using Linux, please follow this instruction: https://github.com/nphdang/GE-FSG/tree/master/For_Linux

**Comment by iiphenoix** [comment]
Thank you for your answer.I also want to use Windows . My computer have installed Microsoft .NET Framework 4,but still can not open fsg_miner.exe .By the way,if fsg_miner.exe running on windows whether or not  it is implemented in parallel?

**Comment by nphdang** [comment]
To run "fsg_miner.exe", you need to use Windows console (please refer to this link: https://www.computerhope.com/issues/chusedos.htm). 
If you store that file in "C:\Downloads" folder, you first open the Windows command line (use "cmd" program) and then type "cd C:\Downloads". After changing the directory to "C:\Downloads", you just need to type "fsg_miner.exe".
Hope it helps.

**Comment by nphdang** [comment]
"fsg_miner.exe" is implemented in parallel on both Windows and Linux.

**Comment by iiphenoix** [comment]
Thank you . It worked.
