### ISSUE TITLE
fsg_miner.zip

### ISSUE THREAD

**Issue by horvathr** [nphdang/GE-FSG#4]
we would like to replace fsg_miner.zip written is C-SHARP with our custom gspan code written Java.

Would it be possible to provide a sample output of fsg_miner so we can format our output  to match the fsg_miner.

**Comment by nphdang** [comment]
The output of "fsg_miner" is text file with the name format "<dataset_name>_graph_fsg_<min_sup>.txt" e.g. "ptc_graph_fsg_0.45.txt".
Each line in the text file is a graph represented by its belonging frequent subgraph IDs, which has the format: 
> <label> <tab> <a set of frequent subgraph IDs>
For example, the first line in the text file is
> 1 <tab> 1 <space> 2 <space> 74
meaning, this is the first graph, it has label "1", and it contains three frequent subgraphs with IDs "1", "2", and "74".

**Comment by nphdang** [comment]
The output of "fsg_miner" is a text file with the name format: "{dataset}_ graph_fsg_{min_sup}.txt", for example "ptc_graph_fsg_0.45.txt".

Each line in the text file is a graph represented by its belonging frequent subgraph IDs, which has the format: {label} {tab} {a set of frequent subgraph IDs}.

For example, if the first line in the text file is "1 {tab} 1 {space} 2 {space} 74". It means that this is the first graph in the dataset, it has label "1", and it contains three frequent subgraphs with IDs "1", "2", and "74".

This is a sample output:
> 1 {tab} 1 2 74
> 1 {tab} 1 3 5 11 13 14 15 16 17 23 59 62 71 73 77
> 1 {tab} 1 2 3 4 5 6 7 8 11 12 74 75 77 78

**Comment by horvathr** [comment]
Thank you very much for the explanation.
